service: lambda-chatgpt
plugins:
  -  serverless-plugin-typescript
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stackName: lambda-chatgpt
  region: ap-southeast-2
  versionFunctions: false
  deploymentBucket: my-mini-lambda-deployments
  environment: 
    OPENAI_KEY: ${env:OPENAI_KEY}
   

functions:
  matchName:
    handler: handler.main
    url: true